#!/usr/bin/env bash
# gen-lint-index.sh — generates toolbelt/INDEX.md, the lint index, from each toolbelt/lint-*.sh header.
#
# BUILD-LOOP §5/§6.b used to enumerate every lint inline; each new lint edited that enumeration
# (a merge-conflict hotspot) and the prose drifted. The index is now DERIVED: one row per
# toolbelt/lint-*.sh with its header description, Usage:, Exit contract, [ev: ...] tags and
# whether report-module.sh runs it automatically. Prose never enumerates lints or counts them.
# [ev: retro kit-meta-hygiene-2026-10-01 Δ3]
#
# Header contract (lines 1-60 of every lint-*.sh):
#   line 2      # <script-name> — <what it checks>   (continuation lines joined until a blank '#')
#   Usage line  # Usage: <script-name> [flags] <arg>
#   Exit line   # Exit: ... | # Exits: ... | # Exit <code> ...
# A lint missing any of the three is a contract violation (exit 1, nothing written).
#
# Mutation: GLI-stale -- dropping the generated-vs-committed compare makes --check vacuously clean
#
# Usage:  gen-lint-index.sh [--check] [<kit-root>]     (default kit root: this script's ../)
# Exits:  0 written / index fresh · 1 stale or missing index under --check, or header-contract
#         violation · 3 usage/env (K20)
# VCS-free by design (kit-links L2). Deterministic: LC_ALL=C sort, no timestamps.
set -u
LC_ALL=C
export LC_ALL

usage_exit() {
  printf 'usage: gen-lint-index.sh [--check] [<kit-root>]\n' >&2
  exit 3
}

CHECK=0
ROOT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --check) CHECK=1; shift ;;
    -*) usage_exit ;;
    *) [ -z "$ROOT" ] || usage_exit; ROOT="$1"; shift ;;
  esac
done
if [ -z "$ROOT" ]; then
  ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
TB="$ROOT/toolbelt"
[ -d "$TB" ] || { printf 'gen-lint-index: no toolbelt/ under %s\n' "$ROOT" >&2; exit 3; }
OUT="$TB/INDEX.md"

# Extract "desc<TAB>usage<TAB>exit<TAB>ev" from one header, or "ERR<TAB><reason>".
extract() {  # file name
  awk -v name="$2" '
    function clean(s) { gsub(/\|/, "\\|", s); gsub(/[[:space:]]+/, " ", s); sub(/^ /, "", s); sub(/ $/, "", s); return s }
    function strip_ev(s) { gsub(/\[ev: [^]]*\]/, "", s); return s }
    NR > 60 { exit }
    {
      line = $0
      tmp = line
      while (match(tmp, /\[ev: [^]]*\]/)) {
        tag = substr(tmp, RSTART, RLENGTH)
        if (!(tag in seen)) { seen[tag] = 1; ev = ev (ev == "" ? "" : " ") tag }
        tmp = substr(tmp, RSTART + RLENGTH)
      }
    }
    NR == 2 {
      pre = "# " name
      if (index(line, pre) == 1) {
        rest = substr(line, length(pre) + 1)
        if (sub(/^[[:space:]]*(—|--|-)[[:space:]]*/, "", rest)) { desc = rest; joining = 1 }
      }
      next
    }
    joining && NR <= 5 {
      if (line ~ /^#[[:space:]]*$/ || line !~ /^#/ || line ~ /^#[[:space:]]*(Usage|Exits?|Scope|Mutation|Row)/) { joining = 0 }
      else { t = line; sub(/^#[[:space:]]*/, "", t); desc = desc " " t }
    }
    usage == "" && line ~ /^#[[:space:]]*Usage:/ { u = line; sub(/^#[[:space:]]*Usage:[[:space:]]*/, "", u); usage = u }
    exitc == "" && line ~ /^#[[:space:]]*Exits?[:[:space:]]/ { x = line; sub(/^#[[:space:]]*Exits?:?[[:space:]]*/, "", x); exitc = x }
    END {
      if (desc == "")  { printf "ERR\tline 2 is not \"# %s — <what it checks>\"\n", name; exit }
      if (usage == "") { printf "ERR\tno \"# Usage:\" line in the header (lines 1-60)\n"; exit }
      if (exitc == "") { printf "ERR\tno \"# Exit:\"/\"# Exits:\" line in the header (lines 1-60)\n"; exit }
      printf "%s\t%s\t%s\t%s\n", clean(strip_ev(desc)), clean(usage), clean(exitc), clean(ev)
    }
  ' "$1"
}

render() {
  cat <<'EOF'
<!-- GENERATED by toolbelt/gen-lint-index.sh from each toolbelt/lint-*.sh header. Do not edit by hand. -->
<!-- Regenerate: bash toolbelt/gen-lint-index.sh · CI freshness gate: bash toolbelt/gen-lint-index.sh --check -->
# Toolbelt lint index

One row per `toolbelt/lint-*.sh`, derived from the script's own header: the description (line 2,
`# <name> — <what it checks>`), the first `Usage:` line, the first `Exit:`/`Exits:` line and any
`[ev: ...]` tags. **Auto** says whether `report-module.sh` (run by `build.sh` after every successful
build) already runs the lint; a `no` lint is run by hand on the profiles its usage names.

To add a lint: write its header to this contract, regenerate, commit both. Never edit this file and
never enumerate or count lints in BUILD-LOOP.md prose. [ev: retro kit-meta-hygiene-2026-10-01 Δ3]

| Lint | What it checks | Usage | Exit contract | Auto | Evidence |
|---|---|---|---|---|---|
EOF
  local f name row desc usage exitc ev auto ucell
  for f in "$TB"/lint-*.sh; do
    [ -f "$f" ] || continue
    name="$(basename "$f")"
    row="$(extract "$f" "$name")"
    case "$row" in
      ERR*) printf 'gen-lint-index: %s: %s\n' "$name" "${row#ERR?}" >&2; printf '%s\n' "$BAD_MARK"; continue ;;
    esac
    IFS='	' read -r desc usage exitc ev <<<"$row"
    auto=no
    if [ -f "$TB/report-module.sh" ] && grep -qF "$name" "$TB/report-module.sh"; then auto=yes; fi
    case "$usage" in *'`'*) ucell="$usage" ;; *) ucell="\`$usage\`" ;; esac
    # shellcheck disable=SC2016  # literal backticks are Markdown code-span delimiters
    printf '| `toolbelt/%s` | %s | %s | %s | %s | %s |\n' "$name" "$desc" "$ucell" "$exitc" "$auto" "${ev:-—}"
  done
}

BAD_MARK='@@gen-lint-index-contract-violation@@'
CONTENT="$(render)"
case "$CONTENT" in *"$BAD_MARK"*) { printf 'gen-lint-index: header-contract violation; index not written\n' >&2; exit 1; } ;; esac

if [ "$CHECK" -eq 1 ]; then
  if [ ! -f "$OUT" ]; then
    printf 'gen-lint-index: %s is missing; run gen-lint-index.sh\n' "$OUT" >&2
    exit 1
  fi
  if [ "$CONTENT" != "$(cat "$OUT")" ]; then
    printf 'gen-lint-index: %s is stale; run gen-lint-index.sh and commit the result\n' "$OUT" >&2
    diff <(printf '%s\n' "$CONTENT") "$OUT" >&2 || true
    exit 1
  fi
  printf 'gen-lint-index: %s is fresh\n' "$OUT"
  exit 0
fi

printf '%s\n' "$CONTENT" > "$OUT"
printf 'gen-lint-index: wrote %s\n' "$OUT"
