#!/usr/bin/env bats
# Tests for build-n4-module-kit/toolbelt/gen-lint-index.sh — the GENERATED lint index.
# BUILD-LOOP §5/§6.b used to enumerate every lint inline (a merge-conflict hotspot that drifts);
# the index is now generated from each toolbelt/lint-*.sh header (description line, Usage:,
# Exit:/Exits:, [ev: ...] tags) into toolbelt/INDEX.md, and `--check` fails when it is stale.
# Exits: 0 written / fresh · 1 stale index or header-contract violation · 3 usage/env.
# [ev: retro kit-meta-hygiene-2026-10-01 Δ3]

setup() {
  TMPDIR_T="$(mktemp -d)"; export TMPDIR_T
  KIT="$(cd "$BATS_TEST_DIRNAME/.." && pwd)/build-n4-module-kit"
  GEN="$KIT/toolbelt/gen-lint-index.sh"
  FK="$TMPDIR_T/kit"
  mkdir -p "$FK/toolbelt"
}
teardown() { rm -rf "$TMPDIR_T"; }

# _mklint <name> <description> [usage] [exit]  — writes a fixture lint header into the fake kit.
_mklint() {
  local n="$1" d="$2" u="${3-$1 <src-root>}" e="${4-0 clean · 1 any FAIL · 3 usage/env}"
  {
    printf '#!/usr/bin/env bash\n# %s — %s\n#\n' "$n" "$d"
    [ -n "$u" ] && printf '# Usage:  %s\n' "$u"
    [ -n "$e" ] && printf '#   Exit: %s\n' "$e"
    printf 'exit 0\n'
  } > "$FK/toolbelt/$n"
}

@test "GLI-usage: an unknown flag or extra args exit 3" {
  run bash "$GEN" --bogus "$FK"
  [ "$status" -eq 3 ]
  run bash "$GEN" "$FK" "$FK"
  [ "$status" -eq 3 ]
}

@test "GLI-env: a kit root with no toolbelt/ exits 3" {
  run bash "$GEN" "$TMPDIR_T/nope"
  [ "$status" -eq 3 ]
}

@test "GLI-rows: one row per toolbelt/lint-*.sh; non-lint scripts are not indexed" {
  _mklint lint-alpha.sh "flags alpha things."
  _mklint lint-beta.sh "flags beta things."
  printf '#!/usr/bin/env bash\n# helper.sh — not a lint\n' > "$FK/toolbelt/helper.sh"
  run bash "$GEN" "$FK"
  [ "$status" -eq 0 ]
  [ -f "$FK/toolbelt/INDEX.md" ]
  [ "$(grep -c '^| `toolbelt/lint-' "$FK/toolbelt/INDEX.md")" -eq 2 ]
  grep -qF 'toolbelt/lint-alpha.sh' "$FK/toolbelt/INDEX.md"
  grep -qF 'toolbelt/lint-beta.sh' "$FK/toolbelt/INDEX.md"
  run grep -qF 'helper.sh' "$FK/toolbelt/INDEX.md"
  [ "$status" -eq 1 ]
  grep -q '^<!-- GENERATED by toolbelt/gen-lint-index.sh' "$FK/toolbelt/INDEX.md"
}

@test "GLI-fields: a row carries the header description, usage, exit contract and [ev:] tags" {
  _mklint lint-gamma.sh "flags gamma [ev: retro some-retro-stem Δ2]" "lint-gamma.sh [--strict] <src-root>" "0 no WARN · 1 any WARN under --strict · 3 usage/env"
  run bash "$GEN" "$FK"
  [ "$status" -eq 0 ]
  row=$(grep -F 'toolbelt/lint-gamma.sh' "$FK/toolbelt/INDEX.md")
  [[ "$row" == *"flags gamma"* ]]
  # shellcheck disable=SC2016  # literal backticks: Markdown code span
  [[ "$row" == *'`lint-gamma.sh [--strict] <src-root>`'* ]]
  [[ "$row" == *"0 no WARN · 1 any WARN under --strict · 3 usage/env"* ]]
  [[ "$row" == *"[ev: retro some-retro-stem Δ2]"* ]]
}

@test "GLI-wrap: a description continued on the next header line is joined" {
  printf '#!/usr/bin/env bash\n# lint-delta.sh — flags delta things that\n# span two header lines.\n#\n# Usage: lint-delta.sh <src>\n# Exits: 0 clean · 3 usage\n' > "$FK/toolbelt/lint-delta.sh"
  run bash "$GEN" "$FK"
  [ "$status" -eq 0 ]
  grep -F 'toolbelt/lint-delta.sh' "$FK/toolbelt/INDEX.md" | grep -qF 'flags delta things that span two header lines.'
}

@test "GLI-pipe: a literal | in a header is escaped so the table row stays intact" {
  _mklint lint-pipe.sh "flags a || b" "lint-pipe.sh <src>" "0 clean | 1 any FAIL | 3 usage"
  run bash "$GEN" "$FK"
  [ "$status" -eq 0 ]
  row=$(grep -F 'toolbelt/lint-pipe.sh' "$FK/toolbelt/INDEX.md")
  [[ "$row" == *'a \|\| b'* ]]
  [[ "$row" == *'0 clean \| 1 any FAIL \| 3 usage'* ]]
}

@test "GLI-contract: a lint header with no Usage: line fails (exit 1) and names the script" {
  _mklint lint-ok.sh "fine."
  _mklint lint-nousage.sh "no usage line." ""
  run bash "$GEN" "$FK"
  [ "$status" -eq 1 ]
  [[ "$output" == *"lint-nousage.sh"* ]]
  [[ "$output" == *"Usage"* ]]
}

@test "GLI-contract-exit: a lint header with no Exit line fails (exit 1)" {
  _mklint lint-noexit.sh "no exit line." "lint-noexit.sh <src>" ""
  run bash "$GEN" "$FK"
  [ "$status" -eq 1 ]
  [[ "$output" == *"lint-noexit.sh"* ]]
}

@test "GLI-fresh: --check exits 0 right after a generate, and a re-generate is byte-identical" {
  _mklint lint-alpha.sh "flags alpha things."
  bash "$GEN" "$FK"
  cp "$FK/toolbelt/INDEX.md" "$TMPDIR_T/first.md"
  run bash "$GEN" --check "$FK"
  [ "$status" -eq 0 ]
  bash "$GEN" "$FK"
  cmp "$TMPDIR_T/first.md" "$FK/toolbelt/INDEX.md"
}

@test "GLI-stale: --check exits 1 when a lint is added without regenerating the index" {
  # Mutation pin: if --check stops comparing the generated text against INDEX.md, this flips GREEN->RED.
  _mklint lint-alpha.sh "flags alpha things."
  bash "$GEN" "$FK"
  _mklint lint-new.sh "a lint landed without regenerating."
  run bash "$GEN" --check "$FK"
  [ "$status" -eq 1 ]
  [[ "$output" == *"stale"* ]]
}

@test "GLI-missing: --check exits 1 when INDEX.md does not exist" {
  _mklint lint-alpha.sh "flags alpha things."
  run bash "$GEN" --check "$FK"
  [ "$status" -eq 1 ]
  [ ! -f "$FK/toolbelt/INDEX.md" ]
}

@test "GLI-check-readonly: --check never writes INDEX.md" {
  _mklint lint-alpha.sh "flags alpha things."
  bash "$GEN" "$FK"
  _mklint lint-new.sh "new."
  cp "$FK/toolbelt/INDEX.md" "$TMPDIR_T/before.md"
  run bash "$GEN" --check "$FK"
  cmp "$TMPDIR_T/before.md" "$FK/toolbelt/INDEX.md"
}

@test "GLI-real: the committed kit toolbelt/INDEX.md is fresh (default kit root)" {
  run bash "$GEN" --check
  [ "$status" -eq 0 ]
}

# polish-2026-10-02 P2b (#199 WU6b): the lint-write-path exit cell was cut mid-sentence ("· 1 any
# uncovered, or any") because its Exits contract wrapped onto a second header line and the index keeps
# the first line only (a general multi-line fix is P4). The header now holds the contract on one line.
@test "GLI-wp: the committed INDEX row for lint-write-path carries the full exit contract (0 · 1 · 3)" {
  # shellcheck disable=SC2016  # literal markdown backticks, not a command substitution
  run grep -F '| `toolbelt/lint-write-path.sh` |' "$KIT/toolbelt/INDEX.md"
  [ "$status" -eq 0 ]
  [[ "$output" == *"under --strict · 3 usage/env/missing-matrix or a sub-directory find cannot enter (K20) |"* ]]
}

# polish-2026-10-02 P4 (#199 WU0 / WU0b): the Auto column matches a real invocation, every Usage/Exit
# header line is kept (wrapped continuations joined), the description join cap is documented and an
# awk failure is an error.

@test "GLI-auto: Auto is yes only for a real \$TOOLBELT/<lint> invocation, not a comment, a message or a longer name" {
  _mklint lint-alpha.sh "invoked."
  _mklint lint-beta.sh "named in a comment only."
  _mklint lint-gamma.sh "named in a message string only."
  _mklint lint-al.sh "a prefix of an invoked name."
  cat > "$FK/toolbelt/report-module.sh" <<'RM'
#!/usr/bin/env bash
# lint-beta.sh is documented here but never run.
a_out=$("$TOOLBELT/lint-alpha.sh" "$ADIR/src" 2>&1) || a_exit=$?
echo "run lint-gamma.sh manually"
RM
  run bash "$GEN" "$FK"
  [ "$status" -eq 0 ]
  # shellcheck disable=SC2016  # literal backticks: Markdown code span
  grep -F '| `toolbelt/lint-alpha.sh` |' "$FK/toolbelt/INDEX.md" | grep -qF '| yes |'
  for n in lint-beta.sh lint-gamma.sh lint-al.sh; do
    row=$(grep -F "| \`toolbelt/$n\` |" "$FK/toolbelt/INDEX.md")
    if [[ "$row" != *"| no |"* ]]; then return 1; fi
  done
}

@test "GLI-wrap-exit: an Exit contract wrapped onto an aligned continuation line is kept whole" {
  printf '#!/usr/bin/env bash\n# lint-wrap.sh — wraps its exit contract.\n#\n# Usage:  lint-wrap.sh <src>\n#   Scans the tree (explanation, not part of the usage).\n# Exits:  0 clean · 1 any FAIL, or any\n#         STALE under --strict · 3 usage/env\n# VCS-free by design.\n' > "$FK/toolbelt/lint-wrap.sh"
  run bash "$GEN" "$FK"
  [ "$status" -eq 0 ]
  row=$(grep -F 'toolbelt/lint-wrap.sh' "$FK/toolbelt/INDEX.md")
  [[ "$row" == *'| 0 clean · 1 any FAIL, or any STALE under --strict · 3 usage/env |'* ]]
  # shellcheck disable=SC2016  # literal backticks: Markdown code span
  [[ "$row" == *'| `lint-wrap.sh <src>` |'* ]]
}

@test "GLI-multi: every Usage and Exit line of the header is kept, in order" {
  printf '#!/usr/bin/env bash\n# lint-two.sh — has two usages and two exit lines.\n#\n# Usage: lint-two.sh <src>\n# Usage: lint-two.sh --strict <src>\n# Exit: 0 clean · 1 any FAIL\n# Exit: 2 usage · 3 env\n' > "$FK/toolbelt/lint-two.sh"
  run bash "$GEN" "$FK"
  [ "$status" -eq 0 ]
  row=$(grep -F 'toolbelt/lint-two.sh' "$FK/toolbelt/INDEX.md")
  # shellcheck disable=SC2016  # literal backticks: Markdown code span
  [[ "$row" == *'| `lint-two.sh <src>`<br>`lint-two.sh --strict <src>` |'* ]]
  [[ "$row" == *'| 0 clean · 1 any FAIL<br>2 usage · 3 env |'* ]]
}

@test "GLI-cap: the description joins at most header lines 2-5 (documented cap)" {
  printf '#!/usr/bin/env bash\n# lint-long.sh — one\n# two\n# three\n# four\n# five-is-past-the-cap\n#\n# Usage: lint-long.sh <src>\n# Exit: 0 clean\n' > "$FK/toolbelt/lint-long.sh"
  run bash "$GEN" "$FK"
  [ "$status" -eq 0 ]
  row=$(grep -F 'toolbelt/lint-long.sh' "$FK/toolbelt/INDEX.md")
  [[ "$row" == *'| one two three four |'* ]]
  grep -q 'lines 2-5' "$GEN"
}

@test "GLI-awkfail: an awk failure exits 3 and leaves the committed INDEX.md untouched" {
  _mklint lint-alpha.sh "flags alpha things."
  bash "$GEN" "$FK"
  cp "$FK/toolbelt/INDEX.md" "$TMPDIR_T/before.md"
  _mklint lint-new.sh "new lint, index would change."
  mkdir -p "$TMPDIR_T/bin"
  printf '#!/bin/sh\nexit 2\n' > "$TMPDIR_T/bin/awk"
  chmod +x "$TMPDIR_T/bin/awk"
  PATH="$TMPDIR_T/bin:$PATH" run bash "$GEN" "$FK"
  [ "$status" -eq 3 ]
  [[ "$output" == *"awk"* ]]
  cmp "$TMPDIR_T/before.md" "$FK/toolbelt/INDEX.md"
}

@test "GLI-timers: the committed INDEX row for lint-timers carries its full exit contract (2 usage · 3 env)" {
  # shellcheck disable=SC2016  # literal markdown backticks, not a command substitution
  run grep -F '| `toolbelt/lint-timers.sh` |' "$KIT/toolbelt/INDEX.md"
  [ "$status" -eq 0 ]
  [[ "$output" == *"2 usage · 3 env |"* ]]
}
