#!/usr/bin/env bats
# Tests for build-n4-module-kit/toolbelt/gen-lint-index.sh — the GENERATED lint index.
# BUILD-LOOP §5/§6.b used to enumerate every lint inline (a merge-conflict hotspot that drifts);
# the index is now generated from each toolbelt/lint-*.sh header (description line, Usage:,
# Exit:/Exits:, [ev: ...] tags) into toolbelt/INDEX.md, and `--check` fails when it is stale.
# Exits: 0 written / fresh · 1 stale index or header-contract violation · 3 usage/env.
# [ev: retro 2026-10-01-kit-meta-hygiene-2026-10-01 Δ3]

setup() {
  TMPDIR_T="$(mktemp -d)"; export TMPDIR_T
  KIT="$(cd "$BATS_TEST_DIRNAME/.." && pwd)/build-n4-module-kit"
  GEN="$KIT/toolbelt/gen-lint-index.sh"
  FK="$TMPDIR_T/kit"
  mkdir -p "$FK/toolbelt"
}
teardown() { rm -rf "$TMPDIR_T"; }

# _mklint <name> <description> [usage] [exit]  — writes a fixture lint header into the fake kit.
_mklint() {
  local n="$1" d="$2" u="${3-$1 <src-root>}" e="${4-0 clean · 1 any FAIL · 3 usage/env}"
  {
    printf '#!/usr/bin/env bash\n# %s — %s\n#\n' "$n" "$d"
    [ -n "$u" ] && printf '# Usage:  %s\n' "$u"
    [ -n "$e" ] && printf '#   Exit: %s\n' "$e"
    printf 'exit 0\n'
  } > "$FK/toolbelt/$n"
}

@test "GLI-usage: an unknown flag or extra args exit 3" {
  run bash "$GEN" --bogus "$FK"
  [ "$status" -eq 3 ]
  run bash "$GEN" "$FK" "$FK"
  [ "$status" -eq 3 ]
}

@test "GLI-env: a kit root with no toolbelt/ exits 3" {
  run bash "$GEN" "$TMPDIR_T/nope"
  [ "$status" -eq 3 ]
}

@test "GLI-rows: one row per toolbelt/lint-*.sh; non-lint scripts are not indexed" {
  _mklint lint-alpha.sh "flags alpha things."
  _mklint lint-beta.sh "flags beta things."
  printf '#!/usr/bin/env bash\n# helper.sh — not a lint\n' > "$FK/toolbelt/helper.sh"
  run bash "$GEN" "$FK"
  [ "$status" -eq 0 ]
  [ -f "$FK/toolbelt/INDEX.md" ]
  [ "$(grep -c '^| `toolbelt/lint-' "$FK/toolbelt/INDEX.md")" -eq 2 ]
  grep -qF 'toolbelt/lint-alpha.sh' "$FK/toolbelt/INDEX.md"
  grep -qF 'toolbelt/lint-beta.sh' "$FK/toolbelt/INDEX.md"
  run grep -qF 'helper.sh' "$FK/toolbelt/INDEX.md"
  [ "$status" -eq 1 ]
  grep -q '^<!-- GENERATED by toolbelt/gen-lint-index.sh' "$FK/toolbelt/INDEX.md"
}

@test "GLI-fields: a row carries the header description, usage, exit contract and [ev:] tags" {
  _mklint lint-gamma.sh "flags gamma [ev: retro some-retro-stem Δ2]" "lint-gamma.sh [--strict] <src-root>" "0 no WARN · 1 any WARN under --strict · 3 usage/env"
  run bash "$GEN" "$FK"
  [ "$status" -eq 0 ]
  row=$(grep -F 'toolbelt/lint-gamma.sh' "$FK/toolbelt/INDEX.md")
  [[ "$row" == *"flags gamma"* ]]
  # shellcheck disable=SC2016  # literal backticks: Markdown code span
  [[ "$row" == *'`lint-gamma.sh [--strict] <src-root>`'* ]]
  [[ "$row" == *"0 no WARN · 1 any WARN under --strict · 3 usage/env"* ]]
  [[ "$row" == *"[ev: retro some-retro-stem Δ2]"* ]]
}

@test "GLI-wrap: a description continued on the next header line is joined" {
  printf '#!/usr/bin/env bash\n# lint-delta.sh — flags delta things that\n# span two header lines.\n#\n# Usage: lint-delta.sh <src>\n# Exits: 0 clean · 3 usage\n' > "$FK/toolbelt/lint-delta.sh"
  run bash "$GEN" "$FK"
  [ "$status" -eq 0 ]
  grep -F 'toolbelt/lint-delta.sh' "$FK/toolbelt/INDEX.md" | grep -qF 'flags delta things that span two header lines.'
}

@test "GLI-pipe: a literal | in a header is escaped so the table row stays intact" {
  _mklint lint-pipe.sh "flags a || b" "lint-pipe.sh <src>" "0 clean | 1 any FAIL | 3 usage"
  run bash "$GEN" "$FK"
  [ "$status" -eq 0 ]
  row=$(grep -F 'toolbelt/lint-pipe.sh' "$FK/toolbelt/INDEX.md")
  [[ "$row" == *'a \|\| b'* ]]
  [[ "$row" == *'0 clean \| 1 any FAIL \| 3 usage'* ]]
}

@test "GLI-contract: a lint header with no Usage: line fails (exit 1) and names the script" {
  _mklint lint-ok.sh "fine."
  _mklint lint-nousage.sh "no usage line." ""
  run bash "$GEN" "$FK"
  [ "$status" -eq 1 ]
  [[ "$output" == *"lint-nousage.sh"* ]]
  [[ "$output" == *"Usage"* ]]
}

@test "GLI-contract-exit: a lint header with no Exit line fails (exit 1)" {
  _mklint lint-noexit.sh "no exit line." "lint-noexit.sh <src>" ""
  run bash "$GEN" "$FK"
  [ "$status" -eq 1 ]
  [[ "$output" == *"lint-noexit.sh"* ]]
}

@test "GLI-fresh: --check exits 0 right after a generate, and a re-generate is byte-identical" {
  _mklint lint-alpha.sh "flags alpha things."
  bash "$GEN" "$FK"
  cp "$FK/toolbelt/INDEX.md" "$TMPDIR_T/first.md"
  run bash "$GEN" --check "$FK"
  [ "$status" -eq 0 ]
  bash "$GEN" "$FK"
  cmp "$TMPDIR_T/first.md" "$FK/toolbelt/INDEX.md"
}

@test "GLI-stale: --check exits 1 when a lint is added without regenerating the index" {
  # Mutation pin: if --check stops comparing the generated text against INDEX.md, this flips GREEN->RED.
  _mklint lint-alpha.sh "flags alpha things."
  bash "$GEN" "$FK"
  _mklint lint-new.sh "a lint landed without regenerating."
  run bash "$GEN" --check "$FK"
  [ "$status" -eq 1 ]
  [[ "$output" == *"stale"* ]]
}

@test "GLI-missing: --check exits 1 when INDEX.md does not exist" {
  _mklint lint-alpha.sh "flags alpha things."
  run bash "$GEN" --check "$FK"
  [ "$status" -eq 1 ]
  [ ! -f "$FK/toolbelt/INDEX.md" ]
}

@test "GLI-check-readonly: --check never writes INDEX.md" {
  _mklint lint-alpha.sh "flags alpha things."
  bash "$GEN" "$FK"
  _mklint lint-new.sh "new."
  cp "$FK/toolbelt/INDEX.md" "$TMPDIR_T/before.md"
  run bash "$GEN" --check "$FK"
  cmp "$TMPDIR_T/before.md" "$FK/toolbelt/INDEX.md"
}

@test "GLI-real: the committed kit toolbelt/INDEX.md is fresh (default kit root)" {
  run bash "$GEN" --check
  [ "$status" -eq 0 ]
}
