package com.angeles.MinimalPan;
import javax.baja.sys.*;
import javax.baja.nre.annotations.*;
@NiagaraType
@NiagaraProperty(name="targetTemp", type="double", defaultValue="0.0", flags=Flags.SUMMARY|Flags.OPERATOR)
@NiagaraProperty(name="interval", type="baja:RelTime", defaultValue="BRelTime.makeSeconds(30)")
@NiagaraAction(name="tickExpired", flags=Flags.HIDDEN)
public class BMinimalPan extends BComponent {
  // slot AUTO region generated by slotomatic at build; omitted in the slot-diff fixture
  public void doTickExpired() {}
}
